version: "3.8"

services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8001:8000"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mysql
      - redis
      - rabbitmq
    command: sh /var/www/entrypoint.sh

  product-service:
    build:
      context: ./product-service
    ports:
      - "8002:8000"
    env_file:
      - ./product-service/.env
    depends_on:
      - mysql
      - redis
      - rabbitmq
    command: sh /var/www/entrypoint.sh

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mysql_data:
